urls.py
# Please try to keep this file organized. Ground rules:
#     * Use include() wherever practical.
#     * If, for whatever reason, URL regular expressions start overriding each
#       other, please make a note of it so it's easier to track down any
#       potential bugs later. (This assumes it's intentional. If it isn't, may
#       God have mercy on your soul.)

# Standard URLconf import
from django.conf.urls.defaults import *

# Imports from Django
from django.conf import settings

# Admin site
from django.contrib.gis import admin
admin.autodiscover()

#import mobileadmin
#mobileadmin.autoregister()

urlpatterns = patterns('',
#    (r'^admin/filebrowser/', include('filebrowser.urls')),
#    (r'^admin_tools/', include('admin_tools.urls')),
    (r'^admin/', include(admin.site.urls)),
#    (r'^grappelli/', include('grappelli.urls')),
)

#urlpatterns += patterns('',
#    (r'^ma/(.*)', mobileadmin.sites.site.root),
#)

# Core
urlpatterns += patterns('',
    (r'^$', 'brubeck.management.views.render_frontpage'),
    (r'^editorial-cartoons/', include('brubeck.core.image_views.urls'), {'mediatype': 'editorialcartoon'}),
    (r'^graphics/', include('brubeck.core.image_views.urls'), {'mediatype': 'graphic'}),
    (r'^issues/', include('brubeck.core.image_views.urls')),
    (r'^layouts/', include('brubeck.core.image_views.urls'), {'mediatype': 'layout'}),
    (r'^photos/', include('brubeck.core.image_views.urls'), {'mediatype': 'photo'}),
    (r'^section/', include('brubeck.publishing.urls_sections')),
    (r'^staff/', include('brubeck.personnel.urls')),
    (r'^stories/', include('brubeck.articles.urls')),
    (r'^tags/', include('brubeck.tagging.urls')),
    (r'^multimedia/(?P<page>[-\w]+)/$', 'brubeck.multimedia.views.top_multimedia'),
    (r'^multimedia/$', 'brubeck.multimedia.views.top_multimedia'),
    #(r'^top-online/$', 'brubeck.management.views.top_online'),
)

# Multimedia
#     These first three patterns override the first line of the URLconf that's
#     included immediately afterward. This is intentional, since we'd like
#     to use a view other than brubeck.core.image_views.views.detail.
urlpatterns += patterns('brubeck.multimedia.views',
    url(r'^videos/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<id>\d+)/$', 'detail', {'mediatype': 'video'}, name='multimedia-video-detail'),
    url(r'^slideshows/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<id>\d+)/$', 'detail', {'mediatype': 'slideshow'}, name='multimedia-slideshow-detail'),
    url(r'^audio/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<id>\d+)/$', 'detail', {'mediatype': 'audioclip'}, name='multimedia-audioclip-detail'),
)
urlpatterns += patterns('',
    (r'^videos/', include('brubeck.core.image_views.urls'), {'mediatype': 'video'}),
    (r'^slideshows/', include('brubeck.core.image_views.urls'), {'mediatype': 'slideshow'}),
    (r'^audio/', include('brubeck.core.image_views.urls'), {'mediatype': 'audioclip'}),
)

# E-mail forms
#     Usually, the view should be 'handle_form_and_email'. If you'd like to
#     restrict it to staff members, use 'restricted_email' (and set
#     'editor_required' to True if only editors should have access to it).
from django.contrib.sites.models import Site
site = Site.objects.get_current()
site_name = site.name
from brubeck.core.emailing.forms import *
urlpatterns += patterns('brubeck.core.emailing.views',
    (r'^photo-request/$', 'restricted_email', {
        'form': PhotoRequestForm,
        'form_template': 'emailing/photorequest/form.html',
        'message_template': 'emailing/photorequest/message.txt',
        'subject': "Photo request",
        'recipients': [settings.EDITORS['photo']],
        'editor_required': True,
        'uses_captcha': False
    }),
    (r'^about/contact/$', 'handle_form_and_email', {
        'form': SubmissionForm,
        'form_template': 'emailing/submission/form.html',
        'message_template': 'emailing/submission/message.txt',
        'subject': "Submission to %s" % site_name,
        'recipients': [settings.EDITORS['chief']],
        'sender': 'self'
    }),
    (r'^section/forum/send-letter/$', 'handle_form_and_email', {
        'form': LetterToTheEditorForm,
        'form_template': 'emailing/lettertotheeditor/form.html',
        'message_template': 'emailing/lettertotheeditor/message.txt',
        'subject': "Letter to the editor",
        'recipients': [settings.EDITORS['forum']]
    }),
    (r'^system-test/$', 'handle_form_and_email', {
        'form': SystemTestForm,
        'form_template': 'emailing/systemtest/form.html',
        'message_template': 'emailing/systemtest/message.txt',
        'subject': "System test",
        'recipients': [settings.EDITORS['online_dev']]
    }),
)
urlpatterns += patterns('django.views.generic.simple',
    (r'^thanks/$', 'direct_to_template', {'template': 'emailing/thanks.html'}),
)

# Other applications
urlpatterns += patterns('',
    # User controls (using django-registration)
    #(r'^accounts/', include('registration.urls')),
    # Blogs
    (r'^blogs/', include('brubeck.blogs.urls')),
    # Calendar
    (r'^calendar/', include('brubeck.events.urls')),
    # Comments (using django.contrib.comments)
    (r'^comments/', include('django.contrib.comments.urls')),
    # Comics
    (r'^comics/', include('brubeck.comics.urls')),
    # Form to e-mail articles and blog posts
    (r'^email/(?P<content_type>[-\w]+)/(?P<content_id>\d+)/$', 'brubeck.core.emailing.views.email_content'),
    # Game answers
    (r'^games/', include('brubeck.games.urls')),
    # Attached maps
    (r'^maps/', include('brubeck.mapping.urls')),
    # Podcasts
    (r'^podcasts/', include('brubeck.podcasts.urls')),
    # Polls
    (r'^polls/', include('brubeck.voxpopuli.urls_polls')),
    # Reporters' database
    (r'^reporters/', include('brubeck.reporters.urls')),
    # Surveys
    (r'^surveys/', include('brubeck.voxpopuli.urls_surveys')),
)

# Feeds
from brubeck.articles.feeds import ArticleFeed
from brubeck.blogs.feeds import BlogFeed
from brubeck.podcasts.feeds import PodcastFeed
from brubeck.publishing.feeds import SectionFeed
from brubeck.tagging.feeds import TagFeed
feeds = {
    'blogs': BlogFeed,
    'latest': ArticleFeed,
    'podcasts': PodcastFeed,
    'sections': SectionFeed,
    'tags': TagFeed,
}
urlpatterns += patterns('',
    (r'^feeds/$', 'brubeck.syndication.views.feeds'),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
)

urlpatterns += patterns('',
    (r'^api/', include('brubeck.api_urls')),
)

docs/models.py
# Imports from Django.
from django.contrib.sites.models import Site
from django.db import models

# Imports from other dependencies. For now, Grappelli's 'PositionField.'
# from positions.fields import PositionField

# Imports from Brubeck.
from brubeck.core.models import Category, ContentChannel, Content
from brubeck.personnel.models import Staffer
from brubeck.publishing.models import Publication, Volume
from brubeck.tagging.models import Tag

# Create your models here.

class BookType(Category):

    def __unicode__(self):
        return self.name

class Book(ContentChannel):
    contributors = models.ManyToManyField(Staffer)
    introductory_message = models.TextField(blank=True, null=True)
    is_update = models.BooleanField()
    pdf = models.FileField(upload_to='manuals/%Y-%m', blank=True, null=True)
    pub_date = models.DateField(auto_now_add=True)
    publication = models.ManyToManyField(Publication, null=True)
    site = models.ManyToManyField(Site, null=True)
    type = models.ForeignKey(BookType)
    volume = models.ManyToManyField(Volume, null=True)

    def __unicode__(self):
        return self.name

class Entry(models.Model):
    book = models.ManyToManyField(Book)
    justification = models.TextField(blank=True, null=True)
###    mistaken_values = models.TextField()
    order_by = models.CharField(max_length=1)
    slug = models.SlugField()
    tags = models.ManyToManyField(Tag, blank=True, null=True, related_name='docs_entry_set')
    text = models.TextField()
    title = models.CharField(max_length=400)

    class Meta:
        verbose_name_plural = 'Entries'

    def __unicode__(self):
        return self.title

class Example(models.Model):
    EXAMPLE_CHOICES = (
        ('P', 'Preferred usage'),
        ('A', 'Accepted (not preferred) usage'),
        ('I', 'Incorrect usage')
    )
    entry = models.ForeignKey(Entry)
    explanation = models.CharField(max_length=400)
    priority = models.SmallIntegerField()
    type = models.CharField(max_length=1, choices=EXAMPLE_CHOICES)
    usage = models.CharField(max_length=400)

    def __unicode__(self):
        return '%s %s' % (self.entry, self.get_type_display())

photography/models.py
# Allow the use of / operator for division to yield floats instead of integers:
# http://docs.python.org/whatsnew/2.2.html#pep-238-changing-the-division-operator
from __future__ import division

# Imports from standard libraries
from datetime import date, timedelta
import hashlib
import os
import urllib2

# Imports from Django
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.markup.templatetags.markup import markdown
from django.contrib.sites.models import Site
from django.core.files import File
from django.contrib.gis.db import models
from django.utils import simplejson

# Imports from maneater
from brubeck.core.models import Content

# Imports from other sources
from pyPdf import PdfFileReader, PdfFileWriter

class Photo(Content):
    """
    Provides support for photos.
    """
    title = models.CharField(max_length=150, blank=True, null=True, help_text="Optional. Used if this photo will be featured alone on a front page of the site.")
    issue = models.ForeignKey('publishing.Issue', db_index=True, help_text="The issue in which this photo was published.")
    section = models.ForeignKey('publishing.Section', db_index=True)
    mugshot = models.BooleanField(default=False, help_text="Is this photo a mugshot? (This is generally only true if the photo is for a crime story.)")
    illustration = models.BooleanField(default=False, help_text="Is this a photo illustration?")
    image = models.ImageField(upload_to='%Y/%m%d/photos', help_text="Accepts JPEG, GIF or PNG file formats.")
    cutline = models.TextField(blank=True)
    tags = models.ManyToManyField('tagging.Tag', blank=True, null=True, help_text="Tags that describe this photo.")
    
    mediatype = 'photo'
    
    def __unicode__(self):
        """
        Returns the base filename (without directory or extension.
        """
        try:
            return u'%s' % imaging.get_filename_components(self.image)['file_base']
        except:
            return u'Image not found'

    def get_prowl_url(self):
        return '/renters-guide/photos/%s/%s/%s/%s/' % (self.pub_date.year, self.pub_date.month, self.pub_date.day, self.id)

    def get_absolute_url(self):
        return '/photos/%s/%s/%s/%s/' % (self.pub_date.year, self.pub_date.month, self.pub_date.day, self.id)

    class Meta:
        get_latest_by = 'pub_date'
        ordering = ['-pub_date', 'section', 'image']

templates/photography/image_detail.html
{% extends "base.html" %}
{% load markup %}{% load core %}

{% block title %}{{ block.super }} &ndash; {% if image.title %}{{ image.title }}{% else %}{% ifequal image.mediatype 'editorialcartoon' %}Editorial cartoon{% else %}{{ image.mediatype|capfirst }}{% endifequal %} from {{ image.pub_date|date:"N j, Y" }}{% endif %}{% endblock title %}

{% block content %}
<h1>{% if image.title %}{{ image.title }}{% else %}{% ifequal image.mediatype 'editorialcartoon' %}Editorial cartoon{% else %}{{ image.mediatype|capfirst }}{% endifequal %} from {{ image.pub_date|date:"N j, Y" }}{% endif %}</h1>
<p class="byline">{% if image.byline %}{% ifequal image.mediatype 'editorialcartoon' %}Illustration by <a href="{{ image.byline.get_absolute_url }}">{{ image.byline }}</a>{% else %}{% if image.illustration %}Photo illustration by {% else %}By {% endif %}{% ifnotequal image.mediatype "layout" %}<a href="{{ image.byline.get_absolute_url }}">{{ image.byline }}</a>/{% ifequal image.mediatype "photo" %}{{ image.byline.photographer_position }}{% else %}Graphic Designer{% endifequal %}{% else %}{% render_byline image.byline %}{% endifnotequal %}{% endifequal %}{% else %}{% if image.static_byline %}{% ifequal image.mediatype 'editorialcartoon' %}Illustration by {% else %}{% if image.illustration %}Photo illustration by {% else %}By {% endif %}{% endifequal %}{{ image.static_byline }}{% endif %}{% endif %}</p>
<div class="wide_photo_container">
    <img class="photo" src="{% ifnotequal image.mediatype "layout" %}{{ image.image.url }}{% else %}{{ image.get_thumbnail500_url }}{% endifnotequal %}" alt="{% if image.title %}{{ image.title }}{% else %}{{ image.mediatype|capfirst }} from {{ image.pub_date|date:"N j, Y" }}{% endif %}" />
    {% if image.cutline %}<p class="cutline">{{ image.cutline|markdown }}</p>{% endif %}
</div>
<div class="object_list">
{% ifequal image.mediatype "layout" %}
    <h2 class="header">Contents</h2>
    {% if image.articles.all %}
    <div class="item">
        <h3>Articles</h3>
        <ul>
            {% for article in image.articles.all %}
            <li><a href="{{ article.get_absolute_url }}">{{ article }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if image.photos.all %}
    <div class="item">
        <h3>Photos</h3>
        <ul>
            {% for photo in image.photos.all %}
            <li><a href="{{ photo.get_absolute_url }}"><img class="photo" src="{{ photo.get_thumbnail100_url }}" alt="Photo from {{ photo.pub_date|date:"N j, Y" }}" /></a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if image.photos.all %}
    <div class="item">
        <h3>Graphics</h3>
        <ul>
            {% for graphic in image.graphics.all %}
            <li><a href="{{ graphic.get_absolute_url }}"><img class="photo" src="{{ graphic.get_thumbnail100_url }}" alt="graphic from {{ graphic.pub_date|date:"N j, Y" }}" /></a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
{% else %}
    <h2 class="header">Related media</h2>
    {% if image.article_set.all %}
    <div class="item">
        <h3>Articles</h3>
        <ul>
            {% for article in image.article_set.all %}
            <li><a href="{{ article.get_absolute_url }}">{{ article }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% if image.entry_set.all %}
    <div class="item">
        <h3>Blog posts</h3>
        <ul>
            {% for entry in image.entry_set.all %}
            <li><a href="{{ entry.get_absolute_url }}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
{% endifequal %}
</div>
{% endblock content %}